name: Basic build & Unit test for pull request.

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: tester/go.sum

      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh
      - name: Launch docker for postgres
        working-directory: ./schema/
        run: ./establish.sh

      # test db_initial_test
      - name: Test db_initial_test
        working-directory: ./tester
        run: go test -v db_initial_test.go