name: Test for pull request.
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-db-migration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: tester/go.sum

      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh

      # establish db from main branch
      - name: Checkout main branch to main_branch directory
        uses: actions/checkout@v3
        with:
          path: main_branch
          ref: main

      - name: Launch docker for postgres with main branch schema
        working-directory: ./main_branch/schema/
        run: ./establish.sh

      # apply migration from current pull request
      - name: Run migration script from current pull request
        working-directory: ./schema/
        run: ./apply_update.sh

      # test db_initial_test
      - name: Test db_initial_test
        working-directory: ./tester
        run: go test -v db_initial_test.go